---
version: "3"
services:
  dev:
    build: .
    container_name: weblgtf
    volumes:
      - ./:/usr/src/app
      - ../webgltf:/usr/src/webgltf
      - ../webgltf-sample-models:/usr/src/webgltf-sample-models
      - /usr/src/app/node_modules
    ports:
      - 8081:8080
    restart: unless-stopped
